### ISSUE TITLE
Version 0.9.49 is very slow

### ISSUE THREAD

**Issue by rikonen** [Hammerspoon/hammerspoon.github.io#13]
While waiting for Karabiner to be made Sierra compatible, I'm using Hammerspoon and Karabiner Elements to make caps lock + ijlk work as arrow keys. My config is as below (don't know any Lua so code is probably horrible but it worked fine when I wrote it and didn't bother trying to make it nicer). With version 0.9.48 the config works -- not perfectly (key repeat stops working randomly) but enough to get work done. However, after the 0.9.49 the same config started working very slowly. Key repeat rate is terribly slow and there's lag. I switched back to 0.9.48 and now it performs well again.

```
local function keyCode(modifiers, key)
  return function() hs.eventtap.keyStroke(modifiers, key) end
end

hs.hotkey.bind({"ctrl"}, 'j', keyCode({}, 'left') ,  nil,   keyCode({}, 'left'))
hs.hotkey.bind({"ctrl"}, 'k', keyCode({}, 'down') ,  nil,   keyCode({}, 'down'))
hs.hotkey.bind({"ctrl"}, 'i', keyCode({}, 'up')   ,  nil,   keyCode({}, 'up'))
hs.hotkey.bind({"ctrl"}, 'l', keyCode({}, 'right'),  nil,   keyCode({}, 'right'))

hs.hotkey.bind({"ctrl", "shift"}, 'j', keyCode({"shift"}, 'left') ,  nil,   keyCode({"shift"}, 'left'))
hs.hotkey.bind({"ctrl", "shift"}, 'k', keyCode({"shift"}, 'down') ,  nil,   keyCode({"shift"}, 'down'))
hs.hotkey.bind({"ctrl", "shift"}, 'i', keyCode({"shift"}, 'up')   ,  nil,   keyCode({"shift"}, 'up'))
hs.hotkey.bind({"ctrl", "shift"}, 'l', keyCode({"shift"}, 'right'),  nil,   keyCode({"shift"}, 'right'))

hs.hotkey.bind({"ctrl", "shift", "alt"}, 'j', keyCode({"shift", "alt"}, 'left') ,  nil,   keyCode({"shift", "alt"}, 'left'))
hs.hotkey.bind({"ctrl", "shift", "alt"}, 'k', keyCode({"shift", "alt"}, 'down') ,  nil,   keyCode({"shift", "alt"}, 'down'))
hs.hotkey.bind({"ctrl", "shift", "alt"}, 'i', keyCode({"shift", "alt"}, 'up')   ,  nil,   keyCode({"shift", "alt"}, 'up'))
hs.hotkey.bind({"ctrl", "shift", "alt"}, 'l', keyCode({"shift", "alt"}, 'right'),  nil,   keyCode({"shift", "alt"}, 'right'))

hs.hotkey.bind({"ctrl", "alt"}, 'j', keyCode({"alt"}, 'left') ,  nil,   keyCode({"alt"}, 'left'))
hs.hotkey.bind({"ctrl", "alt"}, 'k', keyCode({"alt"}, 'down') ,  nil,   keyCode({"alt"}, 'down'))
hs.hotkey.bind({"ctrl", "alt"}, 'i', keyCode({"alt"}, 'up')   ,  nil,   keyCode({"alt"}, 'up'))
hs.hotkey.bind({"ctrl", "alt"}, 'l', keyCode({"alt"}, 'right'),  nil,   keyCode({"alt"}, 'right'))
```

**Comment by cmsj** [comment]
Sorry we didn't catch this report earlier - you've filed it against our website repo, the main repo is github.com/Hammerspoon/hammerspoon

If this is still a problem, please refile the issue over there, but I would also note that Karabiner Elements is now very functional on Sierra, and can probably take care of the keyboard remapping features you need, and will do it at a much more appropriate level of the OS than we can do :)
