### ISSUE TITLE
SSL cert issue

### ISSUE THREAD

**Issue by MattSPalmer** [Hammerspoon/hammerspoon.github.io#15]
Chrome reports that the cert for hammerspoon.org is registered to github.com, and is therefore insecure.

![image](https://cloud.githubusercontent.com/assets/490790/24077465/6e13a236-0c24-11e7-8b6e-d04113b12ab5.png)

**Comment by Habbie** [comment]
Hi Matt, where did you find a link to our site that said https?

**Comment by cmsj** [comment]
Yeah, unfortunately we don't support https, because github pages doesn't support it for arbitrary domains.
