### ISSUE TITLE
http://www.hammerspoon.org/Spoons/ doesn't link to SPOONS.md

### ISSUE THREAD

**Issue by kballard** [Hammerspoon/hammerspoon.github.io#16]
The spoons repository page contains nearly all of the header links from the main documentation page, except it's missing the link to SPOONS.md. This is a rather surprising omission as that link is crucial to understanding how to actually use Spoons.

**Comment by cmsj** [comment]
Sorry, completely missed this issue, but good news, we now link to SPOONS.md :)
